# @author: Florian Renfer
# @date: 16.03.2024
# @version: 1.0

# Enable mouse support
set -g mouse on

# Set nvim keybinds for copy mode
set -g mode-keys vi

# Set base index for windows and panes to 1
set -g base-index 1
set -g pane-base-index 1

# Bind CTRL + R to re-source/reload the tmux configuration
bind-key -r r source-file ~/.tmux.conf
